### ISSUE TITLE
Import Entire Sprite Sheet?

### ISSUE THREAD

**Issue by resistthis13** [ProgSys/pg_disatools#9]
I'm just wondering if it would be possible in a later version to make it import an entire sprite sheet, and use the positions of the sprites to determine where each goes.

It takes extremely long to have to do one sprite at a time. I'm also curious if it would be possible to automate the animation replacement this way too.

For example I changed an entire sheet of Laharl's sprites to those used in Disgaea 2, the sprites are the exact same size, but just use more colors.

**Comment by EvenIllusion** [comment]
I think the Sprite Sheet Editor can already do some of what you need.
It is possible to replace an entire sprite sheet if you do the following:

Right click the first sprite of the sheet (top left) and click "import as color"
![screenshot_74](https://cloud.githubusercontent.com/assets/22409226/19064124/b3270f72-89cd-11e6-86ae-a2d2b32148b2.png)
And replace it with an entire 256x256 sheet that has the sprites you want. In my case I prepared this one to replace the first sheet.
![ronin_import1](https://cloud.githubusercontent.com/assets/22409226/19066314/4f50daa8-89de-11e6-9f65-43384b65664b.png)
If you're importing an image with different colors, obviously it will ask if you want to put them in the color table. Click yes. It will then ask you if you want to resize the sprite. Also click yes.
Now the entire sheet will have changed
![screenshot_75](https://cloud.githubusercontent.com/assets/22409226/19066399/b518ec72-89de-11e6-93ff-28a28c2b6e61.png)
The entire sheet is highlighted because you made the top left sprite 256x256, so just resize it back to its original size and you should be good to go.
You may still need to resize a few of the cutouts manually because Disgaea 1's sprite sheets are very different from all the later games.
I don't see a practical way of replacing animations because of this. The best you can do is match the sprite IDs as well as you can with their equivalent from the later games, but you _will_ need to make manual changes to very many animations.

**Comment by ProgSys** [comment]
Automation is pretty hard thing 😞 Maybe if you describe in more detail how the future you want should work I may work it in.

I released a new version (v0.7.0) with some improvements. I added a way to import an entire sprite sheet, so now you can do it without the trick. But this will only work if the image uses one color table.

Also I added a easyer way to replace the sprite in the keyframe. If you select a sprite in the sprite view you now can use 'Replace' or 'Replace fit'.
- Replace will just replace the sprite ID and the color table offset
- Replace fit will also change  the anchor and the scale so the keyframe sprite keeps the same size

It is useful when you want to replace the sprite sheet with a HD version:
![img](https://dl.dropboxusercontent.com/u/33065226/disgaea/wiki/HD%20sprite%20tutorial/replace.png)

To import your laharl sprite sheet with more colors, you can change the number of colors for a existing sprite sheet by clicking the gear icon (![icon](https://dl.dropboxusercontent.com/u/33065226/disgaea/wiki/icons/settings.png)) and selecting a new number of colors. As long your sprite sheet has the same layout you can just import it and repalce the colors.

**Comment by resistthis13** [comment]
Actually this is exactly what I was asking for thanks, since we can now change the colors of the original sprites, and replace they. Since my sprites are in the same structure, they replace the animations mostly automatically besides a few size adjustments.
